# Generated by Django 5.2.4 on 2025-07-19 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='eco_category',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='is_eco_related',
        ),
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.todocategory', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='todocategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Nombre del icono (ej: work, home, shopping)', max_length=50, null=True, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridad'),
        ),
    ]
